//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace WSEmailProxy 
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="MailAttachServiceSoap", Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WSEmailMessage))]
	public class MailAttachService : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		/// <remarks/>
		public MailAttachService() 
		{
			this.Url = "http://localhost/AttachService_4/MailAttachService.asmx";
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/HelloAttach", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string HelloAttach() 
		{
			object[] results = this.Invoke("HelloAttach", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginHelloAttach(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("HelloAttach", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndHelloAttach(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailSend", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public WSEmailStatus WSEmailSend(WSMessageAttach theMessage, System.Xml.XmlElement theSig) 
		{
			object[] results = this.Invoke("WSEmailSend", new object[] {
																		   theMessage,
																		   theSig});
			return ((WSEmailStatus)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginWSEmailSend(WSMessageAttach theMessage, System.Xml.XmlElement theSig, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("WSEmailSend", new object[] {
																	theMessage,
																	theSig}, callback, asyncState);
		}
        
		/// <remarks/>
		public WSEmailStatus EndWSEmailSend(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((WSEmailStatus)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailFetchHeaders", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string WSEmailFetchHeaders() 
		{
			object[] results = this.Invoke("WSEmailFetchHeaders", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginWSEmailFetchHeaders(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("WSEmailFetchHeaders", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndWSEmailFetchHeaders(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailRetrieve", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string WSEmailRetrieve() 
		{
			object[] results = this.Invoke("WSEmailRetrieve", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginWSEmailRetrieve(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("WSEmailRetrieve", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndWSEmailRetrieve(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailDelete", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string WSEmailDelete() 
		{
			object[] results = this.Invoke("WSEmailDelete", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginWSEmailDelete(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("WSEmailDelete", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndWSEmailDelete(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/RequestFederatedToken", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string RequestFederatedToken() 
		{
			object[] results = this.Invoke("RequestFederatedToken", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginRequestFederatedToken(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("RequestFederatedToken", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndRequestFederatedToken(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailRetrieveAttach", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string WSEmailRetrieveAttach() 
		{
			object[] results = this.Invoke("WSEmailRetrieveAttach", new object[0]);
			return ((string)(results[0]));
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginWSEmailRetrieveAttach(System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("WSEmailRetrieveAttach", new object[0], callback, asyncState);
		}
        
		/// <remarks/>
		public string EndWSEmailRetrieveAttach(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	public class WSMessageAttach : WSEmailMessage 
	{
        
		/// <remarks/>
		public FileAttachment[] Fileattachments;
        
		/// <remarks/>
		public Policy policy;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	public class FileAttachment 
	{
        
		/// <remarks/>
		public string ServerUrl;
        
		/// <remarks/>
		public string FileKey;
        
		/// <remarks/>
		public string FileName;
        
		/// <remarks/>
		public string PathName;
        
		/// <remarks/>
		public string FileBase64;
        
		/// <remarks/>
		public string FileHash;
        
		/// <remarks/>
		public long FileSize;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	public class WSEmailStatus 
	{
        
		/// <remarks/>
		public int ResponseCode;
        
		/// <remarks/>
		public string Message;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	public class Policy 
	{
        
		/// <remarks/>
		public int numSubject;
        
		/// <remarks/>
		public int numObject;
        
		/// <remarks/>
		public object[] objects;
        
		/// <remarks/>
		public object[] subjects;
	}
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(WSMessageAttach))]
	public class WSEmailMessage 
	{
        
		/// <remarks/>
		public string Body;
        
		/// <remarks/>
		public string Subject;
        
		/// <remarks/>
		public object[] Recipients;
        
		/// <remarks/>
		public string Sender;
        
		/// <remarks/>
		public string Timestamp;
        
		/// <remarks/>
		public System.Xml.XmlNode[] XmlAttachments;
        
		/// <remarks/>
		public int MessageFlags;
	}
}
