//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace AttachService.localhost1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MailServerSoap", Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public class MailServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MailServer() {
            this.Url = "http://localhost/WSEMailServer_4/MailServer.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/ExecuteExtensionHandler", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement ExecuteExtensionHandler(string ext, System.Xml.XmlElement args) {
            object[] results = this.Invoke("ExecuteExtensionHandler", new object[] {
                        ext,
                        args});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecuteExtensionHandler(string ext, System.Xml.XmlElement args, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ExecuteExtensionHandler", new object[] {
                        ext,
                        args}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlElement EndExecuteExtensionHandler(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailFetchHeaders", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSEmailHeader[] WSEmailFetchHeaders() {
            object[] results = this.Invoke("WSEmailFetchHeaders", new object[0]);
            return ((WSEmailHeader[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSEmailFetchHeaders(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSEmailFetchHeaders", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WSEmailHeader[] EndWSEmailFetchHeaders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSEmailHeader[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailSend", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSEmailStatus WSEmailSend(WSEmailMessage theMessage, System.Xml.XmlElement theSig) {
            object[] results = this.Invoke("WSEmailSend", new object[] {
                        theMessage,
                        theSig});
            return ((WSEmailStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSEmailSend(WSEmailMessage theMessage, System.Xml.XmlElement theSig, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSEmailSend", new object[] {
                        theMessage,
                        theSig}, callback, asyncState);
        }
        
        /// <remarks/>
        public WSEmailStatus EndWSEmailSend(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSEmailStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailDelete", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSEmailStatus WSEmailDelete(int[] messagesToDelete) {
            object[] results = this.Invoke("WSEmailDelete", new object[] {
                        messagesToDelete});
            return ((WSEmailStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSEmailDelete(int[] messagesToDelete, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSEmailDelete", new object[] {
                        messagesToDelete}, callback, asyncState);
        }
        
        /// <remarks/>
        public WSEmailStatus EndWSEmailDelete(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSEmailStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/WSEmail/WSEmailRetrieve", RequestNamespace="http://securitylab.cis.upenn.edu/WSEmail", ResponseNamespace="http://securitylab.cis.upenn.edu/WSEmail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSEmailPackage WSEmailRetrieve(int messageToGet) {
            object[] results = this.Invoke("WSEmailRetrieve", new object[] {
                        messageToGet});
            return ((WSEmailPackage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWSEmailRetrieve(int messageToGet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WSEmailRetrieve", new object[] {
                        messageToGet}, callback, asyncState);
        }
        
        /// <remarks/>
        public WSEmailPackage EndWSEmailRetrieve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WSEmailPackage)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    public class WSEmailHeader {
        
        /// <remarks/>
        public int MessageID;
        
        /// <remarks/>
        public int Flags;
        
        /// <remarks/>
        public string Sender;
        
        /// <remarks/>
        public string Subject;
        
        /// <remarks/>
        public string Timestamp;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    public class WSEmailPackage {
        
        /// <remarks/>
        public int MessageID;
        
        /// <remarks/>
        public WSEmailMessage theMessage;
        
        /// <remarks/>
        public System.Xml.XmlElement sig;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSMessageAttach))]
    public class WSEmailMessage {
        
        /// <remarks/>
        public string Body;
        
        /// <remarks/>
        public string Subject;
        
        /// <remarks/>
        public object[] Recipients;
        
        /// <remarks/>
        public string Sender;
        
        /// <remarks/>
        public string Timestamp;
        
        /// <remarks/>
        public System.Xml.XmlNode[] XmlAttachments;
        
        /// <remarks/>
        public int MessageFlags;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    public class WSMessageAttach : WSEmailMessage {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securitylab.cis.upenn.edu/WSEmail")]
    public class WSEmailStatus {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string Message;
    }
}
