//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//	
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.288.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;
using PennRoutingFilters;
using Microsoft.Web.Services;
using BusinessObjects;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EmployeeInfoSoap", Namespace="http://securitylab.cis.upenn.edu/AuthorizedRouting")]
public class EmployeeInfoProxy : Microsoft.Web.Services.WebServicesClientProtocol {
    
    /// <remarks/>
	public EmployeeInfoProxy() 
	{
		this.Url = "http://localhost/BusinessObjectsService/EmployeeInfo.asmx";
	}
	public EmployeeInfoProxy(string u) {
		this.Url = u;
    }
    
	/// <remarks/>
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/AuthorizedRouting/GetEmployeeInformation", RequestNamespace="http://securitylab.cis.upenn.edu/AuthorizedRouting", ResponseNamespace="http://securitylab.cis.upenn.edu/AuthorizedRouting", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public EmployeeInformation GetEmployeeInformation() 
	{
		object[] results = this.Invoke("GetEmployeeInformation", new object[0]);
		return ((EmployeeInformation)(results[0]));
	}
    
	/// <remarks/>
	public System.IAsyncResult BeginGetEmployeeInformation(System.AsyncCallback callback, object asyncState) 
	{
		return this.BeginInvoke("GetEmployeeInformation", new object[0], callback, asyncState);
	}
    
	/// <remarks/>
	public EmployeeInformation EndGetEmployeeInformation(System.IAsyncResult asyncResult) 
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((EmployeeInformation)(results[0]));
	}

}