//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.288.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;
using BusinessObjects;



/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
[XmlInclude(typeof(Timesheet)), XmlInclude(typeof(PurchaseOrder))]
public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public Service1() {
		this.Url = "http://localhost/BusinessObjectsService/BizTest.asmx";
    }

	/// <remarks/>
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string PostObject(BusinessObject b) 
	{
		object[] results = this.Invoke("PostObject", new object[] {
																	  b});
		return ((string)(results[0]));
	}
    
	/// <remarks/>
	public System.IAsyncResult BeginPostObject(BusinessObject b, System.AsyncCallback callback, object asyncState) 
	{
		return this.BeginInvoke("PostObject", new object[] {
															   b}, callback, asyncState);
	}
    
	/// <remarks/>
	public string EndPostObject(System.IAsyncResult asyncResult) 
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((string)(results[0]));
	}
    
	/// <remarks/>
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTimesheet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public BusinessObject GetTimesheet(BusinessObject b) 
	{
		object[] results = this.Invoke("GetTimesheet", new object[] {
																		b});
		return ((BusinessObject)(results[0]));
	}
    
	/// <remarks/>
	public System.IAsyncResult BeginGetTimesheet(BusinessObject b, System.AsyncCallback callback, object asyncState) 
	{
		return this.BeginInvoke("GetTimesheet", new object[] {
																 b}, callback, asyncState);
	}
    
	/// <remarks/>
	public BusinessObject EndGetTimesheet(System.IAsyncResult asyncResult) 
	{
		object[] results = this.EndInvoke(asyncResult);
		return ((BusinessObject)(results[0]));
	}

	/*

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string PostObject(BusinessObject b) {
        object[] results = this.Invoke("PostObject", new object[] {
                    b});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostObject(BusinessObject b, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostObject", new object[] {
                    b}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndPostObject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
	*/
}

/// <remarks/>

