//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace UserAgent.LicenseDepot {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LicenseDepotSoap", Namespace="http://localhost/LicenseDepot/")]
    public class LicenseDepotWse : Microsoft.Web.Services.WebServicesClientProtocol {
        
        /// <remarks/>
        public LicenseDepotWse() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["UserAgent.LicenseDepot.LicenseDepot"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/LicenseDepot/LicenseDepot.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/LicenseDepot/Deposit", RequestNamespace="http://localhost/LicenseDepot/", ResponseNamespace="http://localhost/LicenseDepot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Deposit(System.Xml.XmlNode lic) {
            object[] results = this.Invoke("Deposit", new object[] {
                        lic});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeposit(System.Xml.XmlNode lic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Deposit", new object[] {
                        lic}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDeposit(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LicenseDepotSoap", Namespace="http://localhost/LicenseDepot/")]
    public class LicenseDepot : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public LicenseDepot() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["UserAgent.LicenseDepot.LicenseDepot"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost/LicenseDepot/LicenseDepot.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/LicenseDepot/Deposit", RequestNamespace="http://localhost/LicenseDepot/", ResponseNamespace="http://localhost/LicenseDepot/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Deposit(System.Xml.XmlNode lic) {
            object[] results = this.Invoke("Deposit", new object[] {
                        lic});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeposit(System.Xml.XmlNode lic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Deposit", new object[] {
                        lic}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndDeposit(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
}
