//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace AdViewer.GLS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GLSSoap", Namespace="http://158.130.67.0/GLS/")]
    public class GLS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GLS() {
            this.Url = "http://158.130.67.0/GLS/GLS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GLS/GetGIS", RequestNamespace="http://158.130.67.0/GLS/", ResponseNamespace="http://158.130.67.0/GLS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGIS() {
            object[] results = this.Invoke("GetGIS", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGIS(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGIS", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetGIS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GLS/GetLoc", RequestNamespace="http://158.130.67.0/GLS/", ResponseNamespace="http://158.130.67.0/GLS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLoc() {
            object[] results = this.Invoke("GetLoc", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLoc(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLoc", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetLoc(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
