//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Merchant.GIS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GISSoap", Namespace="http://158.130.67.0/GIS/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public class GISWse : Microsoft.Web.Services.WebServicesClientProtocol {
        
        /// <remarks/>
        public GISWse() {
            this.Url = "http://localhost/GIS/GIS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RegisterUser", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterUser(User newUser) {
            object[] results = this.Invoke("RegisterUser", new object[] {
                        newUser});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterUser(User newUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterUser", new object[] {
                        newUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRegisterUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RemoveUser", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveUser(User u) {
            object[] results = this.Invoke("RemoveUser", new object[] {
                        u});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRemoveUser(User u, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RemoveUser", new object[] {
                        u}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRemoveUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/GetNewAds", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetNewAds(User u) {
            object[] results = this.Invoke("GetNewAds", new object[] {
                        u});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNewAds(User u, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNewAds", new object[] {
                        u}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGetNewAds(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/getUsers", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getUsers() {
            object[] results = this.Invoke("getUsers", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUsers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUsers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndgetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RegisterMerchant", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterMerchant(POLICY policy) {
            object[] results = this.Invoke("RegisterMerchant", new object[] {
                        policy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterMerchant(POLICY policy, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterMerchant", new object[] {
                        policy}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRegisterMerchant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/SendAd", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendAd(User u, AdMessage ad) {
            object[] results = this.Invoke("SendAd", new object[] {
                        u,
                        ad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendAd(User u, AdMessage ad, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendAd", new object[] {
                        u,
                        ad}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSendAd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/InsecureGetUsers", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] InsecureGetUsers(Merchant merch) {
            object[] results = this.Invoke("InsecureGetUsers", new object[] {
                        merch});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsecureGetUsers(Merchant merch, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsecureGetUsers", new object[] {
                        merch}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndInsecureGetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/InsecureRegisterMerchant", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsecureRegisterMerchant(Merchant merch, POLICY policy) {
            object[] results = this.Invoke("InsecureRegisterMerchant", new object[] {
                        merch,
                        policy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsecureRegisterMerchant(Merchant merch, POLICY policy, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsecureRegisterMerchant", new object[] {
                        merch,
                        policy}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndInsecureRegisterMerchant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GISSoap", Namespace="http://158.130.67.0/GIS/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public class GIS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GIS() {
            this.Url = "http://localhost/GIS/GIS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RegisterUser", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterUser(User newUser) {
            object[] results = this.Invoke("RegisterUser", new object[] {
                        newUser});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterUser(User newUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterUser", new object[] {
                        newUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRegisterUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RemoveUser", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RemoveUser(User u) {
            object[] results = this.Invoke("RemoveUser", new object[] {
                        u});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRemoveUser(User u, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RemoveUser", new object[] {
                        u}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRemoveUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/GetNewAds", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetNewAds(User u) {
            object[] results = this.Invoke("GetNewAds", new object[] {
                        u});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNewAds(User u, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNewAds", new object[] {
                        u}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGetNewAds(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/getUsers", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getUsers() {
            object[] results = this.Invoke("getUsers", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUsers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUsers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndgetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/RegisterMerchant", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterMerchant(POLICY policy) {
            object[] results = this.Invoke("RegisterMerchant", new object[] {
                        policy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterMerchant(POLICY policy, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterMerchant", new object[] {
                        policy}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRegisterMerchant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/SendAd", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendAd(User u, AdMessage ad) {
            object[] results = this.Invoke("SendAd", new object[] {
                        u,
                        ad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendAd(User u, AdMessage ad, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendAd", new object[] {
                        u,
                        ad}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSendAd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/InsecureGetUsers", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] InsecureGetUsers(Merchant merch) {
            object[] results = this.Invoke("InsecureGetUsers", new object[] {
                        merch});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsecureGetUsers(Merchant merch, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsecureGetUsers", new object[] {
                        merch}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndInsecureGetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://158.130.67.0/GIS/InsecureRegisterMerchant", RequestNamespace="http://158.130.67.0/GIS/", ResponseNamespace="http://158.130.67.0/GIS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsecureRegisterMerchant(Merchant merch, POLICY policy) {
            object[] results = this.Invoke("InsecureRegisterMerchant", new object[] {
                        merch,
                        policy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsecureRegisterMerchant(Merchant merch, POLICY policy, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsecureRegisterMerchant", new object[] {
                        merch,
                        policy}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndInsecureRegisterMerchant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class User {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public System.DateTime EntryTime;
        
        /// <remarks/>
        public System.Xml.XmlNode License;
        
        /// <remarks/>
        public string EmailAddress;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class Merchant {
        
        /// <remarks/>
        public string Name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class AdMessage {
        
        /// <remarks/>
        public string AdText;
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public System.DateTime Time;
        
        /// <remarks/>
        public AdType Type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public enum AdType {
        
        /// <remarks/>
        NormalAd,
        
        /// <remarks/>
        OffensiveAd,
        
        /// <remarks/>
        Discount,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class ACCESS {
        
        /// <remarks/>
        public bool nonident;
        
        /// <remarks/>
        public bool all;
        
        /// <remarks/>
        public bool contact_and_other;
        
        /// <remarks/>
        public bool ident_contact;
        
        /// <remarks/>
        public bool other_ident;
        
        /// <remarks/>
        public bool none;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class CATEGORIES {
        
        /// <remarks/>
        public bool physical;
        
        /// <remarks/>
        public bool online;
        
        /// <remarks/>
        public bool uniqueid;
        
        /// <remarks/>
        public bool purchase;
        
        /// <remarks/>
        public bool financial;
        
        /// <remarks/>
        public bool computer;
        
        /// <remarks/>
        public bool navigation;
        
        /// <remarks/>
        public bool interactive;
        
        /// <remarks/>
        public bool demographic;
        
        /// <remarks/>
        public bool content;
        
        /// <remarks/>
        public bool state;
        
        /// <remarks/>
        public bool political;
        
        /// <remarks/>
        public bool health;
        
        /// <remarks/>
        public bool preference;
        
        /// <remarks/>
        public bool location;
        
        /// <remarks/>
        public bool government;
        
        /// <remarks/>
        public string other_category;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class RETENTION {
        
        /// <remarks/>
        public bool no_retention;
        
        /// <remarks/>
        public bool stated_purpose;
        
        /// <remarks/>
        public bool legal_requirement;
        
        /// <remarks/>
        public bool business_practices;
        
        /// <remarks/>
        public bool indefinitely;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class RECIPIENT {
        
        /// <remarks/>
        public bool ours;
        
        /// <remarks/>
        public Element_with_Required delivery;
        
        /// <remarks/>
        public Element_with_Required same;
        
        /// <remarks/>
        public Element_with_Required other_recipient;
        
        /// <remarks/>
        public Element_with_Required unrelated;
        
        /// <remarks/>
        public Element_with_Required _public;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class Element_with_Required {
        
        /// <remarks/>
        public bool present;
        
        /// <remarks/>
        public REQUIRED required;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public enum REQUIRED {
        
        /// <remarks/>
        always,
        
        /// <remarks/>
        opt_in,
        
        /// <remarks/>
        opt_out,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class PURPOSE {
        
        /// <remarks/>
        public bool current;
        
        /// <remarks/>
        public Element_with_Required admin;
        
        /// <remarks/>
        public Element_with_Required develop;
        
        /// <remarks/>
        public Element_with_Required tailoring;
        
        /// <remarks/>
        public Element_with_Required pseudo_analysis;
        
        /// <remarks/>
        public Element_with_Required pseudo_decision;
        
        /// <remarks/>
        public Element_with_Required individual_analysis;
        
        /// <remarks/>
        public Element_with_Required individual_decision;
        
        /// <remarks/>
        public Element_with_Required contact;
        
        /// <remarks/>
        public Element_with_Required telemarketing;
        
        /// <remarks/>
        public Element_with_Required historical;
        
        /// <remarks/>
        public string other_purpose;
        
        /// <remarks/>
        public REQUIRED other_purpose_required;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class STATEMENT {
        
        /// <remarks/>
        public string consequence;
        
        /// <remarks/>
        public bool nonidentifiable;
        
        /// <remarks/>
        public PURPOSE purpose;
        
        /// <remarks/>
        public RECIPIENT recipient;
        
        /// <remarks/>
        public RETENTION retention;
        
        /// <remarks/>
        public CATEGORIES categories;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class REMEDIES {
        
        /// <remarks/>
        public bool correct;
        
        /// <remarks/>
        public bool money;
        
        /// <remarks/>
        public bool law;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class DISPUTES {
        
        /// <remarks/>
        public REMEDIES remedies;
        
        /// <remarks/>
        public RESOLUTION_TYPE resolution_type;
        
        /// <remarks/>
        public string service;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public enum RESOLUTION_TYPE {
        
        /// <remarks/>
        SERVICE,
        
        /// <remarks/>
        INDEPENDENT,
        
        /// <remarks/>
        COURT,
        
        /// <remarks/>
        LAW,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://158.130.67.0/GIS/")]
    public class POLICY {
        
        /// <remarks/>
        public DISPUTES[] m_disputes;
        
        /// <remarks/>
        public STATEMENT[] m_statements;
        
        /// <remarks/>
        public ACCESS access;
    }
}
