/*

Copyright (c) University of Pennsylvania 2004
With permission of Carl A. Gunter, this code can be used for teaching, experimentation,
and research.

Programmer: Kevin Lux

*/

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.288.
// 

using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;

namespace DynamicBizObjects 
{

	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="VerifierSoap", Namespace="http://securitylab.cis.upenn.edu/AuthorizedRouting")]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(MappedItem))]
	[System.Xml.Serialization.XmlIncludeAttribute(typeof(Signature))]
	public class VerifierProxy : Microsoft.Web.Services2.WebServicesClientProtocol 
	{
    
		/// <remarks/>
		public VerifierProxy() 
		{
			this.Url = "http://localhost/BusinessObjectsService/Verifier.asmx";
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://securitylab.cis.upenn.edu/AuthorizedRouting/PostObject", RequestNamespace="http://securitylab.cis.upenn.edu/AuthorizedRouting", ResponseNamespace="http://securitylab.cis.upenn.edu/AuthorizedRouting", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string PostObject(BusinessRequest r) 
		{
			object[] results = this.Invoke("PostObject", new object[] {
																		  r});
			return ((string)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginPostObject(BusinessRequest r, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("PostObject", new object[] {
																   r}, callback, asyncState);
		}
    
		/// <remarks/>
		public string EndPostObject(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}